name: Remove merge label

jobs:
  check-mergability:
    on:
      - pull_request
    env:
      GH_TOKEN:
        ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        name: Checkout feature
        with:
          fetch-depth: 0
      - run: |
          git merge-tree "$(git merge-base ${{ github.event.pull_request.head.sha }} HEAD)" HEAD "${{ github.event.pull_request.head.sha }}"
