name: Remove merge label

on:
  - pull_request_target


permissions:
  contents: read
  pull-requests: write

jobs:
  check-mergability:
    env:
      GH_TOKEN:
        ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          echo hi
          if git merge-tree "$(git merge-base ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})" ${{ github.event.pull_request.head.sha }} "${{ github.event.pull_request.base.sha }}" | grep "^<<<<<<<\|changed in both"; then
            echo unclean merge
          fi
